[client]
showErrorDetails = false

[theme]
primaryColor = "#1d27b5"

# Background color for the main content area.
backgroundColor = "#e6e7f5"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#282829"

# Color used for almost all text.
textColor =  "#4679f0"

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
font = "sans serif"